version: '3.5'

services:

  db:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vinci
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  data: