version: '3.5'
services:

  db:
    image: postgres
    container_name: "postgres"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./database/sql_init.sql:/docker-entrypoint-initdb.d/sql_init.sql

  streamlit:
    build: ./streamlit
    container_name: "streamlit"
    ports:
      - "8501:8501"

  scraper:
    build: ./scraper
    container_name: "scraper"
